import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {plan,apply,verify,restore,resolveResource} from '../skills/adf-project-install/scripts/project.mjs';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const registry=JSON.parse(fs.readFileSync(path.join(repo,'skills/adf-project-install/references/resources.json')));
function digest(folder){const paths=[];function walk(p){for(const n of fs.readdirSync(p)){const f=path.join(p,n);if(fs.statSync(f).isDirectory())walk(f);else paths.push(path.relative(folder,f).split(path.sep).join('/'));}}walk(folder);const h=crypto.createHash('sha256');for(const rel of paths.sort((a,b)=>a.localeCompare(b))){h.update(rel);h.update(fs.readFileSync(path.join(folder,rel)));}return h.digest('hex');}
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'adf-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'.agents'),{recursive:true});fs.cpSync(path.join(repo,'skills'),path.join(root,'.agents/skills'),{recursive:true});const lock={version:1,skills:{}};for(const name of fs.readdirSync(path.join(repo,'skills'))){lock.skills[name]={source:'chungtsai/adf-framework',sourceType:'github',ref:'v5.1.0',skillPath:`skills/${name}/SKILL.md`,computedHash:digest(path.join(root,'.agents/skills',name))};}fs.writeFileSync(path.join(root,'skills-lock.json'),JSON.stringify(lock));return root;}
function write(r,p,s){fs.mkdirSync(path.dirname(path.join(r,p)),{recursive:true});fs.writeFileSync(path.join(r,p),s);}
test('v5.0 migration preserves approved module and custom standard; backups restore old templates',t=>{
 const r=fixture(t);write(r,'modules/a/manifest.yaml','status: APPROVED\n');write(r,'standards/date.md','CUSTOM');write(r,'CLAUDE.md','Custom instructions');
 const resource=registry.resources['template/manifest.yaml'];write(r,'.adf/templates/module/manifest.yaml',fs.readFileSync(path.join(repo,'skills',resource.skill,resource.path)));
 const p=plan(r);assert.deepEqual(p.blockers,[]);const result=apply(r,p);assert.equal(verify(r).status,'verified');
 assert.equal(fs.readFileSync(path.join(r,'modules/a/manifest.yaml'),'utf8'),'status: APPROVED\n');assert.equal(fs.readFileSync(path.join(r,'standards/date.md'),'utf8'),'CUSTOM');
 assert.equal(JSON.parse(fs.readFileSync(path.join(r,'.adf/project.yaml'))).document_schema,'5.0');assert.ok(!fs.existsSync(path.join(r,'.adf/templates')));
 assert.equal(apply(r,plan(r)).status,'already_migrated');restore(r,result.backup);assert.ok(fs.existsSync(path.join(r,'.adf/templates/module/manifest.yaml')));assert.ok(!fs.existsSync(path.join(r,'.adf/project.yaml')));
});
test('read-only plan refuses unknown/custom template and makes no .adf config',t=>{const r=fixture(t);write(r,'.adf/templates/custom.md','Business logic');const p=plan(r);assert.ok(p.blockers.some(s=>s.includes('confirmed relocation')));assert.throws(()=>apply(r,p));assert.ok(!fs.existsSync(path.join(r,'.adf/project.yaml')));});
test('stale and tampered plans are rejected before write',t=>{const r=fixture(t);write(r,'modules/a/spec.md','v1');const p=plan(r);write(r,'modules/a/spec.md','v2');assert.throws(()=>apply(r,p),/Stale/);const fresh=plan(r);fresh.actions.remove_templates=['modules/a/spec.md'];assert.throws(()=>apply(r,fresh),/altered/);assert.ok(!fs.existsSync(path.join(r,'.adf/backups')));});
test('missing dependency and mismatched version block resource access',t=>{const r=fixture(t);fs.rmSync(path.join(r,'.agents/skills/adf-test-generation'),{recursive:true});assert.throws(()=>resolveResource(r,'template/verification/test-cases.md'),/Missing/);assert.ok(plan(r).blockers.length);write(r,'.agents/skills/adf-feature-init/references/release.json','{"version":"9.0"}');assert.throws(()=>resolveResource(r,'template/manifest.yaml'),/Incompatible/);});
test('agent copy conflicts and external symlinks are refused',t=>{const r=fixture(t);fs.mkdirSync(path.join(r,'.claude/skills'),{recursive:true});fs.cpSync(path.join(r,'.agents/skills/adf-feature-init'),path.join(r,'.claude/skills/adf-feature-init'),{recursive:true});write(r,'.claude/skills/adf-feature-init/assets/manifest.yaml','changed');assert.throws(()=>resolveResource(r,'template/manifest.yaml'),/Conflicting/);fs.rmSync(path.join(r,'.claude/skills/adf-feature-init'),{recursive:true});fs.symlinkSync(path.join(repo,'skills/adf-feature-init'),path.join(r,'.claude/skills/adf-feature-init'),'dir');assert.throws(()=>resolveResource(r,'template/manifest.yaml'),/external/);});
test('symlinked templates cannot read/delete outside project',t=>{const r=fixture(t);fs.mkdirSync(path.join(r,'.adf'));fs.symlinkSync(repo,path.join(r,'.adf/templates'),'dir');assert.throws(()=>plan(r),/Symlink/);assert.ok(fs.existsSync(path.join(repo,'README.md')));});
test('rollback refuses edits made after migration',t=>{const r=fixture(t);write(r,'modules/a/spec.md','approved');const result=apply(r,plan(r));write(r,'modules/a/spec.md','new work');assert.throws(()=>restore(r,result.backup),/changed/);assert.equal(fs.readFileSync(path.join(r,'modules/a/spec.md'),'utf8'),'new work');});
test('arbitrary YAML config is preserved and blocks automatic merge',t=>{const r=fixture(t);write(r,'.adf/project.yaml','custom: true\n');assert.ok(plan(r).blockers.some(s=>s.includes('YAML merge')));assert.equal(fs.readFileSync(path.join(r,'.adf/project.yaml'),'utf8'),'custom: true\n');});

test('manual copies without npx source records cannot claim migration completion',t=>{const r=fixture(t);fs.unlinkSync(path.join(r,'skills-lock.json'));assert.ok(plan(r).blockers.some(s=>s.includes('provenance')));assert.throws(()=>apply(r,plan(r)));});
test('raw GitHub v5.0 template byte hash is recognized',t=>{const r=fixture(t);const resource=registry.resources['template/manifest.yaml'];let original=fs.readFileSync(path.join(repo,'skills',resource.skill,resource.path),'utf8');original=original.replace(/\n$/,'');write(r,'.adf/templates/module/manifest.yaml',original);assert.deepEqual(plan(r).blockers,[]);});

test('obsolete active ADF skill and standard legacy references are blockers',t=>{const r=fixture(t);write(r,'.claude/skills/adf-old-custom/SKILL.md','manual');write(r,'standards/reference.md','Read framework/review/approval-gate.md');const p=plan(r);assert.ok(p.blockers.some(s=>s.includes('obsolete')));assert.ok(p.blockers.some(s=>s.includes('legacy standard')));});
test('completed migration is idempotent after normal new work',t=>{const r=fixture(t);write(r,'modules/a/spec.md','approved');apply(r,plan(r));write(r,'modules/a/spec.md','approved new CHANGE');assert.equal(apply(r,plan(r)).status,'already_migrated');assert.equal(verify(r).subsequent_project_changes,true);});
test('confirmed custom information relocation preserves evidence and removes only template copy',t=>{
 const r=fixture(t);write(r,'.adf/templates/custom.md','custom rule');write(r,'standards/project-rule.md','approved custom rule');
 const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
 const entries=[{source:'custom.md',source_hash:sha('custom rule'),destination:'standards/project-rule.md',destination_hash:sha('approved custom rule'),human_confirmed:true}];
 const p=plan(r,{entries});assert.deepEqual(p.blockers,[]);const result=apply(r,p);assert.equal(fs.readFileSync(path.join(r,'standards/project-rule.md'),'utf8'),'approved custom rule');
 assert.equal(fs.readFileSync(path.join(r,'.adf/backups',result.backup,'templates/custom.md'),'utf8'),'custom rule');
});
test('backup tampering blocks restore without removing current config',t=>{const r=fixture(t);const res=apply(r,plan(r));write(r,`.adf/backups/${res.backup}/unexpected.md`,'tampered');assert.throws(()=>restore(r,res.backup),/integrity/);assert.ok(fs.existsSync(path.join(r,'.adf/project.yaml')));});
test('Agent symlink to canonical project owner resolves without duplicate resource',t=>{const r=fixture(t);fs.mkdirSync(path.join(r,'.claude/skills'),{recursive:true});fs.symlinkSync(path.join(r,'.agents/skills/adf-feature-init'),path.join(r,'.claude/skills/adf-feature-init'),'dir');assert.ok(resolveResource(r,'template/manifest.yaml').endsWith('assets/manifest.yaml'));assert.deepEqual(plan(r).blockers,[]);});
test('installed content changes invalidate provenance even when version file stays unchanged',t=>{const r=fixture(t);write(r,'.agents/skills/adf-develop/assets/specification.md','modified');assert.ok(plan(r).blockers.some(s=>s.includes('differs from npx lock')));});

test('legacy project Codex directory must be disabled before completion',t=>{const r=fixture(t);write(r,'.codex/skills/adf-feature-init/SKILL.md','old');assert.ok(plan(r).blockers.some(s=>s.includes('unsupported Agent')));assert.throws(()=>apply(r,plan(r)));});
test('VERIFY rejects newly introduced global conflicts and honors recorded loading evidence',t=>{const r=fixture(t);const home=fs.mkdtempSync(path.join(os.tmpdir(),'adf-home-'));t.after(()=>fs.rmSync(home,{recursive:true,force:true}));t.mock.method(os,'homedir',()=>home);apply(r,plan(r));const g=path.join(home,'.claude/skills/adf-feature-init');fs.mkdirSync(g,{recursive:true});fs.writeFileSync(path.join(g,'SKILL.md'),'old');assert.ok(plan(r).blockers.some(s=>s.includes('Global skill')));assert.throws(()=>verify(r),/Global skill/);});
test('confirmed global disposition survives migration verification',t=>{const r=fixture(t);const home=fs.mkdtempSync(path.join(os.tmpdir(),'adf-home-'));t.after(()=>fs.rmSync(home,{recursive:true,force:true}));t.mock.method(os,'homedir',()=>home);const g=path.join(home,'.claude/skills/adf-feature-init');fs.mkdirSync(g,{recursive:true});fs.writeFileSync(path.join(g,'SKILL.md'),'old');const p=plan(r,{entries:[],global_dispositions:[{path:g,disposition:'project_scope_only',human_confirmed:true,evidence:'Agent configured to load this project only'}]});assert.deepEqual(p.blockers,[]);apply(r,p);assert.equal(verify(r).status,'verified');});
