import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {buildPlan,apply,verify,restore} from '../scripts/migrate-v5-installation.mjs';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'v5-transfer-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const project=path.join(root,'project');fs.mkdirSync(project);const official=path.join(root,'official');fs.mkdirSync(official);fs.cpSync(path.join(repo,'skills'),path.join(official,'skills'),{recursive:true});fs.cpSync(path.join(repo,'framework'),path.join(official,'framework'),{recursive:true});fs.copyFileSync(path.join(repo,'package.json'),path.join(official,'package.json'));return {project,source:{root:official,commit:'a'.repeat(40),requested_ref:'release/v5.0.0-original'}};}
function write(root,p,content){fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),content);}
function digest(root){const files=[];function walk(p){for(const n of fs.readdirSync(p)){const f=path.join(p,n);if(fs.statSync(f).isDirectory())walk(f);else files.push(path.relative(root,f).split(path.sep).join('/'));}}walk(root);const h=crypto.createHash('sha256');for(const p of files.sort((a,b)=>a.localeCompare(b))){h.update(p);h.update(fs.readFileSync(path.join(root,p)));}return h.digest('hex');}
function fakeInstaller(source){return (stage,p)=>{const lock={version:1,skills:{}};for(const n of p.names){const f=path.join(stage,p.agent==='codex'?'.agents/skills':'.claude/skills',n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.cpSync(path.join(source.root,'skills',n),f,{recursive:true});lock.skills[n]={source:'chungtsai/adf-framework',sourceType:'github',ref:p.commit,skillPath:`skills/${n}/SKILL.md`,computedHash:digest(f)};}write(stage,'skills-lock.json',JSON.stringify(lock));};}
test('requires explicit confirmation; no unconfirmed replacement',t=>{const {project:p,source:s}=fixture(t);write(p,'.claude/skills/adf-develop/SKILL.md','CUSTOM');const plan=buildPlan(p,s);assert.ok(plan.differences.some(d=>d.path.includes('adf-develop')));assert.throws(()=>apply(p,s,plan,{installer:fakeInstaller(s)}),/Confirm/);assert.equal(fs.readFileSync(path.join(p,'.claude/skills/adf-develop/SKILL.md'),'utf8'),'CUSTOM');});
test('confirmed custom replacement removes old directory only after successful installation and preserves v5.0 files',t=>{const {project:p,source:s}=fixture(t);write(p,'.codex/skills/adf-develop/SKILL.md','custom old');write(p,'modules/a/manifest.yaml','APPROVED');write(p,'standards/date.md','local rule');write(p,'.adf/templates/custom.md','local template');write(p,'CLAUDE.md','existing guide\n');const plan=buildPlan(p,s);const res=apply(p,s,plan,{confirmed:true,installer:fakeInstaller(s)});assert.equal(verify(p).status,'verified');assert.ok(!fs.existsSync(path.join(p,'.codex/skills/adf-develop')));assert.equal(fs.readFileSync(path.join(p,'modules/a/manifest.yaml'),'utf8'),'APPROVED');assert.equal(fs.readFileSync(path.join(p,'.adf/templates/custom.md'),'utf8'),'local template');assert.equal(fs.readFileSync(path.join(p,'standards/date.md'),'utf8'),'local rule');assert.ok(fs.readFileSync(path.join(p,'CLAUDE.md'),'utf8').startsWith('existing guide\n'));assert.ok(fs.existsSync(path.join(p,'framework/review/approval-gate.md')));restore(p,res.backup);assert.equal(fs.readFileSync(path.join(p,'.codex/skills/adf-develop/SKILL.md'),'utf8'),'custom old');assert.ok(!fs.existsSync(path.join(p,'skills-lock.json')));assert.equal(fs.readFileSync(path.join(p,'CLAUDE.md'),'utf8'),'existing guide\n');});
test('download failure preserves all old skills and creates no project state',t=>{const {project:p,source:s}=fixture(t);write(p,'.claude/skills/adf-develop/SKILL.md','old');const plan=buildPlan(p,s);assert.throws(()=>apply(p,s,plan,{confirmed:true,installer:()=>{throw Error('download failed');}}),/download failed/);assert.equal(fs.readFileSync(path.join(p,'.claude/skills/adf-develop/SKILL.md'),'utf8'),'old');assert.ok(!fs.existsSync(path.join(p,'.adf')));});
test('stale and altered plans cannot replace files',t=>{const {project:p,source:s}=fixture(t);const plan=buildPlan(p,s);write(p,'AGENTS.md','new instruction');assert.throws(()=>apply(p,s,plan,{confirmed:true,installer:fakeInstaller(s)}),/Stale/);const modified=buildPlan(p,s);modified.targets.push('modules/a');assert.throws(()=>apply(p,s,modified,{confirmed:true,installer:fakeInstaller(s)}),/altered/);});
test('source v5.1 is rejected',t=>{const {project:p,source:s}=fixture(t);write(s.root,'package.json','{"version":"5.1.0"}');assert.throws(()=>buildPlan(p,s),/only transfers/);});
test('installed content or provenance mismatch aborts before writes',t=>{const {project:p,source:s}=fixture(t);const plan=buildPlan(p,s);assert.throws(()=>apply(p,s,plan,{confirmed:true,installer:(stage,plan)=>{fakeInstaller(s)(stage,plan);write(stage,'.claude/skills/adf-develop/SKILL.md','wrong');}}),/differs/);assert.ok(!fs.existsSync(path.join(p,'.agents')));});
test('unrelated skills and lock entries survive transfer',t=>{const {project:p,source:s}=fixture(t);write(p,'.agents/skills/other/SKILL.md','other');write(p,'skills-lock.json',JSON.stringify({version:1,skills:{other:{source:'other/repo'}}}));apply(p,s,buildPlan(p,s),{confirmed:true,installer:fakeInstaller(s)});assert.equal(JSON.parse(fs.readFileSync(path.join(p,'skills-lock.json'))).skills.other.source,'other/repo');assert.equal(fs.readFileSync(path.join(p,'.agents/skills/other/SKILL.md'),'utf8'),'other');});
test('safe repeated transfer is no-op after new module work',t=>{const {project:p,source:s}=fixture(t);const plan=buildPlan(p,s);apply(p,s,plan,{confirmed:true,installer:fakeInstaller(s)});write(p,'modules/a/requirements.md','new work');assert.equal(apply(p,s,plan,{confirmed:true,installer:()=>assert.fail('must not reinstall')}).status,'already_transferred');assert.equal(verify(p).subsequent_project_changes,true);});
test('restore refuses subsequent managed-file changes',t=>{const {project:p,source:s}=fixture(t);const res=apply(p,s,buildPlan(p,s),{confirmed:true,installer:fakeInstaller(s)});write(p,'CLAUDE.md','new custom instruction');assert.throws(()=>restore(p,res.backup),/New changes/);assert.equal(fs.readFileSync(path.join(p,'CLAUDE.md'),'utf8'),'new custom instruction');});
test('path traversal, symlinked ancestors and protected legacy containers are rejected',t=>{const {project:p,source:s}=fixture(t);assert.throws(()=>buildPlan(p,s,{legacy:['../skills']}),/dedicated/);assert.throws(()=>buildPlan(p,s,{legacy:['modules/skills']}),/dedicated/);fs.symlinkSync(s.root,path.join(p,'.agents'),'dir');assert.throws(()=>buildPlan(p,s),/Symlink/);});
test('unknown manual ADF skill is listed and removed only with confirmation',t=>{const {project:p,source:s}=fixture(t);write(p,'.codex/skills/adf-old-custom/SKILL.md','manual custom');const plan=buildPlan(p,s);assert.ok(plan.differences.some(d=>d.path.endsWith('adf-old-custom')));const res=apply(p,s,plan,{confirmed:true,installer:fakeInstaller(s)});assert.ok(!fs.existsSync(path.join(p,'.codex/skills/adf-old-custom')));assert.ok(fs.existsSync(path.join(p,'.adf/v5-transfer-backups',res.backup,'files/.codex/skills/adf-old-custom/SKILL.md')));});
test('records functional version separately from management mode',t=>{const {project:p,source:s}=fixture(t);const plan=buildPlan(p,s);assert.equal(plan.adf_version,'5.0.0');assert.equal(plan.management_from,'manual');assert.equal(plan.management_to,'npx-skills');apply(p,s,plan,{confirmed:true,installer:fakeInstaller(s)});const r=JSON.parse(fs.readFileSync(path.join(p,'.adf/v5-transfer.json')));assert.equal(r.adf_version,'5.0.0');assert.equal(r.status,'verified');assert.equal(verify(p).management,'npx-skills');});
test('filesystem failure during replacement restores already-written managed files',t=>{const {project:p,source:s}=fixture(t);write(p,'.claude/skills/adf-develop/SKILL.md','OLD');write(p,'AGENTS.md','original');const plan=buildPlan(p,s);const originalWrite=fs.writeFileSync;let fired=false;t.mock.method(fs,'writeFileSync',function(file,...args){if(!fired&&String(file)===path.join(p,'AGENTS.md')){fired=true;throw new Error('simulated disk error');}return originalWrite.call(fs,file,...args);});assert.throws(()=>apply(p,s,plan,{confirmed:true,installer:fakeInstaller(s)}),/managed files restored/);assert.equal(fs.readFileSync(path.join(p,'.claude/skills/adf-develop/SKILL.md'),'utf8'),'OLD');assert.equal(fs.readFileSync(path.join(p,'AGENTS.md'),'utf8'),'original');assert.ok(!fs.existsSync(path.join(p,'skills-lock.json')));});
test('changed project during staged installation is preserved without committing install',t=>{const {project:p,source:s}=fixture(t);const plan=buildPlan(p,s);assert.throws(()=>apply(p,s,plan,{confirmed:true,installer:(stage,p2)=>{fakeInstaller(s)(stage,p2);write(p,'modules/new/spec.md','USER NEW WORK');}}),/changed while downloading/);assert.equal(fs.readFileSync(path.join(p,'modules/new/spec.md'),'utf8'),'USER NEW WORK');assert.ok(!fs.existsSync(path.join(p,'.agents')));});
test('internal old Agent symlink is backed up and restored as the original link',t=>{const {project:p,source:s}=fixture(t);fs.mkdirSync(path.join(p,'.agents/skills'),{recursive:true});fs.cpSync(path.join(s.root,'skills/adf-develop'),path.join(p,'.agents/skills/adf-develop'),{recursive:true});fs.mkdirSync(path.join(p,'.claude/skills'),{recursive:true});fs.symlinkSync('../../.agents/skills/adf-develop',path.join(p,'.claude/skills/adf-develop'),'dir');const plan=buildPlan(p,s);const res=apply(p,s,plan,{confirmed:true,installer:fakeInstaller(s)});restore(p,res.backup);assert.equal(fs.readlinkSync(path.join(p,'.claude/skills/adf-develop')),'../../.agents/skills/adf-develop');});
